'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XAMPPC2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        '''&lt;ServiceTools&gt;
        '''	&lt;ConfigurationFiles&gt;
        '''		&lt;Config Title=&quot;Apache (httpd.conf)&quot; Source=&quot;%xamppdir%\apache\conf\httpd.conf&quot;/&gt;
        '''		&lt;Config Title=&quot;Apache (httpd-ssl.conf)&quot; Source=&quot;%xamppdir%\apache\conf\extra\httpd-ssl.conf&quot;/&gt;
        '''		&lt;Config Title=&quot;Apache (httpd-xampp.conf)&quot; Source=&quot;%xamppdir%\apache\conf\extra\httpd-xampp.conf&quot;/&gt;
        '''		&lt;Config Title=&quot;PHP (php.ini)&quot; Source=&quot;%xamppdir%\php\php.ini&quot;/&gt;
        '''		&lt;Config Title=&quot;phpMyAdmin (config.inc.php)&quot; Source=&quot;%xamppdir%\phpMyAdmin\conf [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property apache() As String
            Get
                Return ResourceManager.GetString("apache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        '''&lt;ServiceTools&gt;
        '''	&lt;ConfigurationFiles&gt;
        '''		&lt;Config Title=&quot;FileZilla Server.xml&quot; Source=&quot;%xamppdir%\FileZillaFTP\FileZilla Server.xml&quot;/&gt;
        '''	&lt;/ConfigurationFiles&gt;
        '''
        '''	&lt;LogFiles&gt;
        '''	&lt;/LogFiles&gt;
        '''
        '''	&lt;WebApplications&gt;
        '''		&lt;WebApp Title=&quot;Správa serveru&quot; Address=&quot;%xamppdir%\filezillaftp\filezilla server interface.exe&quot; /&gt;
        '''	&lt;/WebApplications&gt;
        '''&lt;/ServiceTools&gt;.
        '''</summary>
        Friend ReadOnly Property filezilla() As String
            Get
                Return ResourceManager.GetString("filezilla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        '''&lt;ServiceTools&gt;
        '''	&lt;ConfigurationFiles&gt;
        '''		&lt;Config Title=&quot;MERCURY.INI&quot; Source=&quot;%xamppdir%\MercuryMail\MERCURY.INI&quot;/&gt;
        '''	&lt;/ConfigurationFiles&gt;
        '''
        '''	&lt;LogFiles&gt;
        '''	&lt;/LogFiles&gt;
        '''
        '''	&lt;WebApplications&gt;
        '''	&lt;/WebApplications&gt;
        '''&lt;/ServiceTools&gt;.
        '''</summary>
        Friend ReadOnly Property mercury() As String
            Get
                Return ResourceManager.GetString("mercury", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        '''&lt;ServiceTools&gt;
        '''	&lt;ConfigurationFiles&gt;
        '''		&lt;Config Title=&quot;MySQL (my.ini)&quot; Source=&quot;%xamppdir%\mysql\bin\my.ini&quot;/&gt;
        '''	&lt;/ConfigurationFiles&gt;
        '''
        '''	&lt;LogFiles&gt;
        '''		&lt;Log Title=&quot;MySQL (mysql_error.log)&quot; Source=&quot;%xamppdir%\mysql\data\mysql_error.log&quot; /&gt;
        '''	&lt;/LogFiles&gt;
        '''
        '''	&lt;WebApplications&gt;
        '''		&lt;WebApp Title=&quot;phpMyAdmin&quot; Address=&quot;http://localhost/phpmyadmin&quot; /&gt;
        '''	&lt;/WebApplications&gt;
        '''&lt;/ServiceTools&gt;.
        '''</summary>
        Friend ReadOnly Property mysql() As String
            Get
                Return ResourceManager.GetString("mysql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        '''&lt;ServiceTools&gt;
        '''	&lt;ConfigurationFiles&gt;
        '''		&lt;Config Title=&quot;server.xml&quot; Source=&quot;%xamppdir%\tomcat\conf\server.xml&quot;/&gt;
        '''		&lt;Config Title=&quot;tomcat-users.xml&quot; Source=&quot;%xamppdir%\tomcat\conf\tomcat-users.xml&quot;/&gt;
        '''		&lt;Config Title=&quot;web.xml&quot; Source=&quot;%xamppdir%\tomcat\conf\web.xml&quot;/&gt;
        '''		&lt;Config Title=&quot;context.xml&quot; Source=&quot;%xamppdir%\tomcat\conf\context.xml&quot;/&gt;
        '''	&lt;/ConfigurationFiles&gt;
        '''
        '''	&lt;LogFiles&gt;
        '''	&lt;/LogFiles&gt;
        '''
        '''	&lt;WebApplications&gt;
        '''	&lt;/WebApplications&gt;
        '''&lt;/ServiceTools&gt;.
        '''</summary>
        Friend ReadOnly Property tomcat() As String
            Get
                Return ResourceManager.GetString("tomcat", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
